# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ec4dbca947be281284aeed3b945ba930204f97b6c69d1affee09e6f4d647d06b898edb1cf1b64e6dffba6b59513dc36e3229796f5831b3b216a4decf47bdde3

test:
  secret_key_base: b648912a20d713063bb2768b3299a9a91516ac21d18eb07f34298338130ed24c0520083dcea03e06bdec96c12c2a493125dc05391ed566d38a95623aaea39a3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
